### ISSUE TITLE
A error

### ISSUE THREAD

**Issue by liaomei1995** [BGI-Qingdao/SLR-superscaffolder#4]
Dear sir,

when I test the example data by using SLR-superscaffolder, there occur error in the ./step_2_order.sh. 

"ERROR : step_2  check output file failed !!! exit ...
ERROR : step_2  scaffold_1.soap.mst.barcodeOnBin
ERROR : step_2  please double check above files exist and readable !!!"

and in the chopbin are "terminate called after throwing an instance of 'std::invalid_argument' what():  stod"

And I have checked there was no problem in my GCC. So, could you please show we why this problem occurs.

**Comment by cchd0001** [comment]
Hi ,

Thanks for telling us this bug, we have fixed it by updating the example/config.ini 

Best wishes
Lidong Guo
