### ISSUE TITLE
run unsuccessfully

### ISSUE THREAD

**Issue by baokem** [BGI-Qingdao/SLR-superscaffolder#5]
hello!  

I ran "./run.sh >log_pipeline 2>&1 &" , the program interrupted , there generated four log files,"log_bwa_index,log_bwa_mem,log_parsereadname,log_pipeline" ,the error in last file,
"./step_1_prepare_info.sh：行 23: 140417 已杀死               /home/chenguolin/superSLR/superSLR/bin/Sam2ReadOnContig --prefix NA12878 2>> log_sam2readoncontig",

could you please help me,  thank you !

**Comment by adonis316** [comment]
Hi,
The module Sam2ReadOnContig is used to read SAM files. Seems like the memory is insufficient. Please check the amount of available memory of your PC or cluster, and increase it if your genome size is large and sequencing coverage is high (>50gb RAM for 50x 3g human genome). 

Thanks,
Mengyang

**Comment by baokem** [comment]
Thank you, I will retry it.

**Comment by baokem** [comment]
hello,
I recently used SLR-superscaffolder to scaffolding a fruitfly genome, When running BinCluster step, it runs all the time without error, but no result is generated, and it does not enter the next step. Does it need to run more time, or is there another reason(such as parameters)? the log file shows that BinCluster start now... 
could you please help me, thank you !

**Comment by cchd0001** [comment]
Hi, 

The running time of BinCluster depends on the genome size and the thread number it can use.  It may cost days for a gigabit genome with 30 threads.

Best wishes 
Lidong Guo

**Comment by baokem** [comment]
thanks for your reply！
