### ISSUE TITLE
Can I skip the BWA MEM  and use the BAM file as input？

### ISSUE THREAD

**Issue by baokem** [BGI-Qingdao/SLR-superscaffolder#6]

**Comment by cchd0001** [comment]
Hi,

Assume you have already got the bam of  your input stLFR reads mapped to the target contigs.  In that case you can skip the bwa mem by modifying the step_1_prepare_info.sh :

1. comment out the BWA index and mem commands;
2. convert BAM file to SAM and save with proper filename:
      ```samtools view <your bam>  -o [prefix].read2contig.sam```

Best wishes, 
Lidong Guo

**Comment by baokem** [comment]
thank you for your reply! that is helpful for me.
